version: 0.1

phases:
  pre_build:
    commands:
      - echo "Running GradlewBuild"
      - chmod 755 ./gradlew
      - ./gradlew build
  build:
    commands:
      - echo "Build completed on $(date)"
  post_build:
    commands:
      - echo start post build.
      - mkdir artifacts
      - cp build/libs/SpringSample-0.0.1-SNAPSHOT.jar artifacts
artifacts:
  commands:
    - echo start artifacts 
  files:
    - SpringSample-0.0.1-SNAPSHOT.jar
  base-directory: artifacts