version: 0.1

phases:
  pre_build:
    commands:
      - echo "Running GradlewBuild"
      - chmod 755 ./gradlew
      - ./gradlew build
  build:
    commands:
      - echo "Build completed on $(date)"
